# SPDX-FileCopyrightText: 2023-2026 Slavi Pantaleev
# SPDX-FileCopyrightText: 2025 spatterIight
# SPDX-FileCopyrightText: 2025, 2026 Suguru Hirahara
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---
- name: Ensure Jellyfin paths exist
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "0750"
    owner: "{{ jellyfin_uid }}"
    group: "{{ jellyfin_gid }}"
  with_items:
    - "{{ jellyfin_base_path }}"
    - "{{ jellyfin_data_path }}"

- name: Ensure Jellyfin media path exists
  ansible.builtin.file:
    path: "{{ jellyfin_media_path }}"
    state: directory
    mode: "0750"
    owner: "{{ jellyfin_uid }}"
    group: "{{ jellyfin_gid }}"
  when: jellyfin_media_bind_path | length > 0

- name: Ensure Jellyfin support files created
  ansible.builtin.template:
    src: "{{ role_path }}/templates/{{ item }}.j2"
    dest: "{{ jellyfin_base_path }}/{{ item }}"
    mode: "0640"
    owner: "{{ jellyfin_uid }}"
    group: "{{ jellyfin_gid }}"
  with_items:
    - env
    - labels
  register: jellyfin_support_files_result

- name: Ensure Jellyfin container image is pulled via community.docker.docker_image_pull
  when: devture_systemd_docker_base_container_image_pull_method == 'ansible-module'
  community.docker.docker_image_pull:
    name: "{{ jellyfin_container_image }}"
    pull: always
  register: jellyfin_container_image_pull_result_ansible_module
  retries: "{{ devture_playbook_help_container_retries_count }}"
  delay: "{{ devture_playbook_help_container_retries_delay }}"
  until: jellyfin_container_image_pull_result_ansible_module is not failed

- name: Ensure Jellyfin container image is pulled via ansible.builtin.command
  when: devture_systemd_docker_base_container_image_pull_method == 'command'
  ansible.builtin.command:
    cmd: "{{ devture_systemd_docker_base_host_command_docker }} pull {{ jellyfin_container_image }}"
  register: jellyfin_container_image_pull_result_command
  retries: "{{ devture_playbook_help_container_retries_count }}"
  delay: "{{ devture_playbook_help_container_retries_delay }}"
  until: jellyfin_container_image_pull_result_command is not failed
  changed_when: "'Downloaded newer image' in jellyfin_container_image_pull_result_command.stdout"

- name: Ensure Jellyfin container network is created via community.docker.docker_network
  when: devture_systemd_docker_base_container_network_creation_method == 'ansible-module'
  community.docker.docker_network:
    enable_ipv6: "{{ devture_systemd_docker_base_ipv6_enabled }}"
    name: "{{ jellyfin_container_network }}"
    driver: bridge
    driver_options: "{{ devture_systemd_docker_base_container_networks_driver_options }}"
  register: jellyfin_network_creation_result

- name: Ensure Jellyfin container network is created via ansible.builtin.command
  when: devture_systemd_docker_base_container_network_creation_method == 'command'
  ansible.builtin.command:
    cmd: >-
      {{ devture_systemd_docker_base_host_command_docker }} network create
      {% if devture_systemd_docker_base_ipv6_enabled %}--ipv6{% endif %}
      {{ devture_systemd_docker_base_container_networks_driver_options_string }}
      {{ jellyfin_container_network }}
  register: jellyfin_network_creation_result
  changed_when: jellyfin_network_creation_result.rc == 0
  failed_when: jellyfin_network_creation_result.rc != 0 and 'already exists' not in jellyfin_network_creation_result.stderr

- name: Ensure Jellyfin systemd service is present
  ansible.builtin.template:
    src: "{{ role_path }}/templates/systemd/jellyfin.service.j2"
    dest: "{{ devture_systemd_docker_base_systemd_path }}/{{ jellyfin_identifier }}.service"
    mode: "0644"
  register: jellyfin_systemd_service_result

- name: Determine whether Jellyfin needs a restart
  ansible.builtin.set_fact:
    jellyfin_restart_necessary: >-
      {{
        jellyfin_support_files_result.changed | default(false)
        or jellyfin_systemd_service_result.changed | default(false)
        or jellyfin_container_image_pull_result_ansible_module.changed | default(false)
        or jellyfin_container_image_pull_result_command.changed | default(false)
      }}
