---

- name: Fail if required Jellyfin settings not defined
  ansible.builtin.fail:
    msg: >
      You need to define a required configuration setting (`{{ item }}`).
  when: "vars[item] | length == 0"
  with_items:
    - jellyfin_uid
    - jellyfin_gid
    - jellyfin_hostname

- name: Fail if Jellyfin architecture is not supported
  ansible.builtin.fail:
    msg: >
      Your configuration specifies a CPU architecture (`{{ jellyfin_arch }}`) which is not currently supported.
      This Jellyfin role also does not support self-building yet, so it's not possible to make use of it.
  when: "jellyfin_arch not in ['amd64', 'arm64']"

- name: Validate Jellyfin Traefik configuration
  when: jellyfin_container_labels_traefik_enabled | bool
  block:
    - name: Fail if required Jellyfin Traefik settings not defined
      ansible.builtin.fail:
        msg: >-
          You need to define a required configuration setting (`{{ item }}`).
      when: "vars[item] == ''"
      with_items:
        - jellyfin_container_labels_traefik_hostname
        - jellyfin_container_labels_traefik_path_prefix

    # We ensure it doesn't end with a slash, because we handle both (slash and no-slash).
    # Knowing that `jellyfin_container_labels_traefik_path_prefix` does not end with a slash
    # ensures we know how to set these routes up without having to do "does it end with a slash" checks elsewhere.
    - name: Fail if jellyfin_container_labels_traefik_path_prefix ends with a slash
      ansible.builtin.fail:
        msg: >-
          jellyfin_container_labels_traefik_path_prefix (`{{ jellyfin_container_labels_traefik_path_prefix }}`) must either be `/` or not end with a slash (e.g. `/jellyfin`).
      when: "jellyfin_container_labels_traefik_path_prefix != '/' and jellyfin_container_labels_traefik_path_prefix[-1] == '/'"
